name: Deploy images to gh-pages branch

on:
  push:
    paths:
      - 'images/**'
      - '.github/workflows/deploy-images.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      # See doc at https://github.com/actions/checkout#checkout-v2
      - name: Checkout repository
        uses: actions/checkout@v2

      # See doc at https://github.com/marketplace/actions/deploy-to-github-pages
      - name: Deploy images
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: images
          target-folder: images
